---
- name: Check systemd existence as Docker Guest
  ansible.builtin.stat:
    path: /bin/systemctl
  when: ansible_virtualization_role is defined and ansible_virtualization_type == "docker" and ansible_virtualization_role == "guest"
  register: docker_stat_result

- name: Set systemd openvpn service name
  ansible.builtin.set_fact:
    openvpn_service_name: "openvpn@{{ openvpn_config_file }}.service"
  when: ansible_service_mgr == "systemd" or (docker_stat_result.stat is defined and docker_stat_result.stat.exists)
